export const selectorPage = (state) => state.cars.page;
export const selectorCars = (state) => state.cars.items;
export const selectorError = (state) => state.cars.error;
export const selectorBrands = (state) => state.cars.brands;
export const selectorFavorite = (state) => state.cars.favorite;
export const selectorOpenMenu = (state) => state.cars.isOpenMenu;
export const selectorIsLoading = (state) => state.cars.isLoading;
export const selectorTotalPages = (state) => state.cars.totalPages;
export const selectorSelectedCar = (state) => state.cars.selectedCar;
